---

- name: 'apply configuration'
  template: src='my.cnf.j2' dest='/etc/my.cnf' owner='root' group='root' mode=644
  register: mycnf

- name: 'how many times has rebooted'
  shell: 'last reboot | grep -w "reboot" | wc -l'
  register: reg_reboot_counter

- debug: var=reg_reboot_counter

- name: Run mysqld
  service:
    name: 'mysqld'
    state: restarted
    enabled: yes
  when: reg_reboot_counter.stdout|int == 1
  
- name: get root password
  shell: "grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | awk -F ' ' '{print $(NF)}'"
  register: tmp_root_password
  ignore_errors: true

- name: debug tmp_root_password
  debug:
    var: tmp_root_password

- name: debug temporal mysql password
  debug:
    var: tmp_root_password
  when: tmp_root_password.stdout != ""

- name: update expired root user password
  command: "mysql --user root --password={{ tmp_root_password.stdout }} --connect-expired-password --execute=\"ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql.root_password }}'; UPDATE mysql.user SET Host='%' WHERE Host='localhost' AND User='root';\""
  when: tmp_root_password.stdout != ""

- name: delete /var/log/mysqld.log
  file: 
    path: /var/log/mysqld.log
    state: absent
  when: tmp_root_password.stdout != ""

- name: 'Restart mysqld service'
  service:
    name: mysqld 
    state: restarted
  when: tmp_root_password.stdout != ""
